branches:
  only:
    - develop/3.0
    - develop/2.3
    - develop/2.2
    - master/3.0
    - master/2.3
    - master/2.2
environment:
  tag_name: "%APPVEYOR_REPO_TAG_NAME%"
  release_name: "humm-opencart_v%APPVEYOR_REPO_TAG_NAME%.ocmod.zip"
before_build:
  - ps: (Get-Content upload/catalog/model/payment/humm.php).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content upload/catalog/model/payment/humm.php
build_script:
  - ps: Invoke-Expression "7z a $env:release_name upload README.md LICENSE"
artifacts:
  - path: $(release_name)
    name: $(tag_name)
    type: zip
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: v$(APPVEYOR_REPO_TAG_NAME)
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: UaYGIzw09m+5DkdlA5zDuCr5x71z0KFvgquQhFSMxuJiUmltfok5GuMk8aGpG5U6
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - devadmin@shophumm.com.au
      - pit@shophumm.com.au
  - provider: Slack
    auth_token:
      secure: lgjOGAi/xfra+Ezjg696zGwfMyEivWbNo6ho9GwbeQConO2VwxX2txxjWrZVqAaxTtI7y/ODz0HG3uMfIiM5wF2Fa0KsT8I+KL7PW9BbzpQ=
    channel: '#alerts'